<!--NAVIGATION-->
<nav class="navbar navbar-expand-lg navbar-primary bg-dark sticky-top">
    <div class="container">
        <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link font-weight-bold text-light" href="#">Inicio</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link font-weight-bold text-light" href="#">Ver cartelera</a>
                </li>
            </ul>
            <a class="navbar-brand hidden-md-down text-light " href="#">
                <img src="img/logo.png" alt="" width="30px" ></a>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link font-weight-bold text-light" href="#">Proximos estrenos</a>
                </li>
            </ul>
          </div>
    </div>
</nav> <!--END NAVIGATION-->


<!--CAROUSEL-->
<div class="container-fluid">
  <div class="row ">
    <div class="col-sm-12 ">
      <div id="inam" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <?php //Llenar el carousel con portadas de las imagenes que sean estreno
            $count = 0;
            foreach ($peliculas as $pelicula) {
              if($pelicula -> prioridad == "ESTRENO"){                  
            ?>
            <!-- START CAROUSEL ITEMS-->
            <div class="<?php if($count==0){echo 'carousel-item active';}else{echo 'carousel-item';};?>   ">
               <div class="container">
                  <div class="row  justify-content-center"> 
                      <div class="col-sm-12 col-lg-3"><!--ITEM-->
                        <div class="card" style="width: 250px;margin:10px;">
                          <img src="<?php echo $pelicula->imagen;?>" class="card-img-top">
                        </div> 
                      </div> <!--END ITEM--> 
                  </div> <!--ROW--> 
                 </div> <!--CONTAINER--> 
            </div> <!-- END CAROUSEL ITEMS-->
            <?php 
             $count = 1; 
              }//End if
            }//End for             
            //Fin del llenado de carousel ?>


          <a href="#inam" class="carousel-control-prev " href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a href="#inam" class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
        </div> <!--CAROUSEL INNER-->
      </div> <!--INAM-->
    </div> <!--COL SM 12-->
  </div> <!--ROW 1-->
</div> <!--CONTAINER FLUID END CAROUSEL-->


<!--NAV CATEGORIES -->
<div class="container" >
  <ul class="nav nav-tabs  justify-content-center sticky-top-2 bg-light text-dark" id="myTab" role="tablist">
    <?php $count=0; foreach ($categorias as $categoria) {?>
      <li class="nav-item">
        <a class="<?php if($count == 0){ echo 'nav-link active'; }else{echo 'nav-link';}; ?>" id="<?php echo $categoria -> categoria."-tab" ;?>" data-toggle="tab" href="#<?php echo $categoria -> categoria;?>" role="tab" aria-controls="<?php echo $categoria -> categoria;?>" aria-selected="<?php if($count == 0){ echo 'true'; }else{echo 'false';}; ?>"><?php echo $categoria -> categoria;?></a>
      </li>
      <?php $count = 1; } ?>
  </ul>

  <div class="tab-content" id="myTabContent">
      <?php $count=0; foreach ($categorias as $categoria) {?>
        <div class="<?php if($count == 0){ echo 'tab-pane fade show active'; }else{echo 'tab-pane fade';}; ?>" id="<?php echo $categoria -> categoria;?>" role="tabpanel" aria-labelledby="home-tab">
        <div class="container-c">
            <div class="row">
               <?php foreach ($peliculas as  $pelicula) { 
                if($categoria -> id_categoria == $pelicula -> categoria){  
               ?>
                <div class="col-sm-12 col-lg-3"> <!--ITEM -->
                  <div class="card" style="width: 180px;margin:20px;">
                    <img src="<?php echo $pelicula -> imagen;?>" class="card-img-top">
                    <div class="card-body">
                        <button type="button" class="btn btn btn-dark btn-block">Ver</button>
                    </div>
                  </div> 
                </div> <!--END ITEM -->
                <?php }} ?>
            </div> 
        </div>
        </div>
      <?php $count = 1; } ?>
  </div>
</div> <!-- END NAV CATEGORIES-->


