<!--NAVIGATION-->
<?php $dias=""; $horario=""; $date =$_REQUEST["date"];?>
<nav class="navbar navbar-expand-lg navbar-primary bg-primary sticky-top">
    <div class="container">
        <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link font-weight-bold text-light" href="client">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold text-light" href="#">Ver cartelera</a>
                </li>
            </ul>
            <a class="navbar-brand hidden-md-down text-light " href="#">
                <img src="img/logo.png" alt="" width="30px"></a>
            <ul class="navbar-nav ml-auto">
                <h5 class="text-primary"> ...........................................</h5>
            </ul>
        </div>
    </div>
</nav>
<!--END NAVIGATION-->
<br>

<div class="container-c">
    <div class="form-group">
        <label for="exampleFormControlSelect1">Buscar por dia:</label>
        <!-- Search form -->
        <form class="form-inline my-2 my-lg-0" methos="get">
            <input class="form-control mr-sm-2" type="search" placeholder="yyyy/mm/dd" aria-label="Search" name="date"
                value="<?php echo $date ?>">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Buscar</button>
        </form>
    </div>
    <h3><label class="text-primary control-label" for="exampleFormControlSelect1"><?php saber_dia($date);?></label></h3>
    <?php $fecha=""; $aux2 =0; $aux=0;  foreach ($proyecciones as $proyeccion) {
     $fecha = "".$proyeccion ->dia  ;
     if($date==$fecha){
     if($aux != $proyeccion->pelicula){    
    ?>

    <div class="card flex-row flex-wrap">
        <div class="card-header border-0">
            <img src="<?php       
            foreach ($peliculas as $pelicula) {
               if($pelicula -> id_pelicula ==  $proyeccion->pelicula ){
                   echo $pelicula -> imagen;
               }
            }
            ?>" style="width: 130px;height=360px;" alt="">
        </div>
        <div class="card-block px-2">
            <h4 class="card-title"><?php  foreach ($peliculas as $pelicula) {
               if($pelicula -> id_pelicula ==  $proyeccion->pelicula ){
                   echo $pelicula -> nombre_pelicula;
               }
            } ?></h4>
            <p class="card-text"><?php foreach ($peliculas as $pelicula) {
               if($pelicula -> id_pelicula ==  $proyeccion->pelicula ){
                   echo $pelicula -> duracion;
               }
            } ?></p>

            <p class="card-text">
                <?php  foreach ($peliculas as $pelicula) {
               if($pelicula -> id_pelicula ==  $proyeccion->pelicula ){
                $id_clasificacion = $pelicula -> clasificacion;
                foreach ($clasificaciones as $clasificacion){
                   if($clasificacion -> id_clasificacion == $id_clasificacion){
                       echo $clasificacion -> clasificacion;
                       }
                    }
               }
            }
              ?>
            </p>
            <p class="card-text"><?php 
            foreach ($peliculas as $pelicula) {
               if($pelicula -> id_pelicula ==  $proyeccion->pelicula ){
                $id_categoria = $pelicula -> categoria;
                foreach ($categorias as $categoria){
                   if($categoria -> id_categoria == $id_categoria){
                       echo $categoria-> categoria;
                       }
                    }
               }
            } ?></p>

            <a href="#" class="btn btn-primary align-self-end">Ver trailer</a>

        </div>

        <div class="card-block px-2 ml-auto ">
        </div>
        <div class="w-100"></div>
        <div class="card-footer w-100 text-muted">
            <h6 class="card-title"><?php echo 'Horarios' ?></h6>
            <h6 class="card-title text-dark"><?php 
            $hora = "";
            $sala = "";
                foreach ($pro as $proyecc) {
                    if($proyecc -> pelicula ==  $proyeccion->pelicula){
                        if($proyecc -> dia == $date){
                            $hora .= "  S".$proyecc -> sala . " a las ".$proyecc -> horario . " | ";
                        }
                    }
                }
             echo $hora;
            ?></h6>
        </div>
    </div>
    <br>

    <?php
        $aux=$proyeccion->pelicula; }else{
         $aux2 = $aux;
         $aux = $proyeccion ->pelicula;
        }//fin de if 
    }else{
        
    }
    }


     function saber_dia($fecha){
        setlocale(LC_TIME,  'es_ES_CO.UTF-8');		
        $newDate = date("d-m-Y", strtotime($fecha));				
        $mesDesc = strftime("%A, %e de %B", strtotime($newDate));
        echo "Funciones del dia ". $mesDesc .".";
    }
    ?>

    <script>
        jQuery(document).ready(function ($) {

        });

        function getval(date) {
            window.location = "cartelera?date=" + date.value;
        }
    </script>
</div>